author:
  email: Baker@Shamlan.sa
  url: ''
  name: Baker Shamlan
title: Information Matters
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0.8124653259292245
  brandStrength: 0
  lightness: 0.9677621552255005
  brandColors:
    - '#000000'
    - '#404040'
    - '#808080'
    - '#BFBFBF'
    - '#FFFFFF'
  rhythmicContrast: 0.8158995821140707
typography_spectrum: 0.7538243520539254
description: Under Development
navigation:
  - name: About
    id: cff52f2f-f989-437d-a272-568e23864d05
    type: content
layout_spectrum: 1
name: Information Matters
