typography_spectrum: 0.7538243520539254
color:
  saturation: 1
  brandStrength: 0
  lightness: 1
  brandColors:
    - '#000000'
    - '#404040'
    - '#808080'
    - '#BFBFBF'
    - '#FFFFFF'
  rhythmicContrast: 1
layout_spectrum: 0.2531915
author:
  email: Baker@Shamlan.sa
  url: ''
  name: Baker Shamlan
name: Information Matters
navigation:
  - name: About
    id: cff52f2f-f989-437d-a272-568e23864d05
    type: content
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
title: Information Matters B.V.
description: 'Hullenbergweg 280-308 1101 BV, Amsterdam The Nether'
